"""initial schema

Revision ID: 1adcd22bbdbd
Revises: 
Create Date: 2026-08-08 15:27:49.185299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1adcd22bbdbd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_ingestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=64), nullable=False),
    sa.Column('source_listing_id', sa.String(length=128), nullable=True),
    sa.Column('parser_version', sa.String(length=32), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_key', 'content_hash', name='uq_raw_source_hash')
    )
    op.create_index(op.f('ix_raw_ingestions_content_hash'), 'raw_ingestions', ['content_hash'], unique=False)
    op.create_index(op.f('ix_raw_ingestions_source_key'), 'raw_ingestions', ['source_key'], unique=False)
    op.create_index(op.f('ix_raw_ingestions_source_listing_id'), 'raw_ingestions', ['source_listing_id'], unique=False)
    op.create_table('sellers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('seller_type', sa.String(length=16), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('zip', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sellers_name_state', 'sellers', ['name', 'state'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('reliability_weight', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_key'), 'sources', ['key'], unique=True)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('trim', sa.String(length=16), nullable=False),
    sa.Column('transmission', sa.String(length=16), nullable=False),
    sa.Column('exterior_color', sa.String(length=64), nullable=True),
    sa.Column('interior_color', sa.String(length=64), nullable=True),
    sa.Column('vin_decoded', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_vin'), 'vehicles', ['vin'], unique=True)
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('source_listing_id', sa.String(length=128), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('stock_number', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'source_listing_id', name='uq_source_listing')
    )
    op.create_index(op.f('ix_listings_seller_id'), 'listings', ['seller_id'], unique=False)
    op.create_index(op.f('ix_listings_source_id'), 'listings', ['source_id'], unique=False)
    op.create_index(op.f('ix_listings_status'), 'listings', ['status'], unique=False)
    op.create_index(op.f('ix_listings_stock_number'), 'listings', ['stock_number'], unique=False)
    op.create_index(op.f('ix_listings_vehicle_id'), 'listings', ['vehicle_id'], unique=False)
    op.create_table('vehicle_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('source_key', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id', 'code', name='uq_vehicle_option')
    )
    op.create_index(op.f('ix_vehicle_options_vehicle_id'), 'vehicle_options', ['vehicle_id'], unique=False)
    op.create_table('listing_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('title_status', sa.String(length=16), nullable=False),
    sa.Column('accident_reported', sa.Boolean(), nullable=True),
    sa.Column('options_raw', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('field_confidence', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('raw_ingestion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['raw_ingestion_id'], ['raw_ingestions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_observations_listing_id'), 'listing_observations', ['listing_id'], unique=False)
    op.create_index(op.f('ix_listing_observations_observed_at'), 'listing_observations', ['observed_at'], unique=False)
    op.create_index('ix_obs_listing_time', 'listing_observations', ['listing_id', 'observed_at'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('sold_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('venue', sa.String(length=64), nullable=True),
    sa.Column('raw_ingestion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['raw_ingestion_id'], ['raw_ingestions.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_vehicle_id'), 'transactions', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_vehicle_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_obs_listing_time', table_name='listing_observations')
    op.drop_index(op.f('ix_listing_observations_observed_at'), table_name='listing_observations')
    op.drop_index(op.f('ix_listing_observations_listing_id'), table_name='listing_observations')
    op.drop_table('listing_observations')
    op.drop_index(op.f('ix_vehicle_options_vehicle_id'), table_name='vehicle_options')
    op.drop_table('vehicle_options')
    op.drop_index(op.f('ix_listings_vehicle_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_stock_number'), table_name='listings')
    op.drop_index(op.f('ix_listings_status'), table_name='listings')
    op.drop_index(op.f('ix_listings_source_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_seller_id'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_vehicles_vin'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_sources_key'), table_name='sources')
    op.drop_table('sources')
    op.drop_index('ix_sellers_name_state', table_name='sellers')
    op.drop_table('sellers')
    op.drop_index(op.f('ix_raw_ingestions_source_listing_id'), table_name='raw_ingestions')
    op.drop_index(op.f('ix_raw_ingestions_source_key'), table_name='raw_ingestions')
    op.drop_index(op.f('ix_raw_ingestions_content_hash'), table_name='raw_ingestions')
    op.drop_table('raw_ingestions')
    # ### end Alembic commands ###
